### ISSUE TITLE
Is it still working on Catalina?

### ISSUE THREAD

**Issue by WangJ509** [ankurpandeyvns/VPNShare#1]
My aim is to share the vpn to my phone over the built-in Internet sharing(via WIFI). After setup for the Ethernet(as in the video), I choose sharing from Ethernet, but my phone just can't get the Internet access. I think it might be the problem that apple has no longer supported ALTQ in kernel. Below is the messages after running ./Share.sh
"""
net.inet.ip.forwarding: 1 -> 1
No ALTQ support in kernel
ALTQ related functions disabled
pf disabled
pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
pf enabled
"""

**Comment by ankurpandeyvns** [comment]
Sorry for checking it super late, It does work on catalina as i checked,
